# Generated by Django 3.0.7 on 2021-02-16 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainDishName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VegetableKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegeName', models.CharField(max_length=50)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetableKind', to='api.VegetableKind')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=500)),
                ('ajitsuke', models.CharField(max_length=200)),
                ('onomatopoeia', models.CharField(max_length=20)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainDish', to='api.MainDish')),
                ('recipeKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeKind', to='api.RecipeKind')),
                ('userRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecipe', to=settings.AUTH_USER_MODEL)),
                ('vegetables', models.ManyToManyField(to='api.Vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('memo', models.CharField(max_length=500)),
                ('userDiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
