# Generated by Django 3.0.7 on 2021-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookingTime',
            field=models.IntegerField(default=0),
        ),
    ]
